In [3]:
# Задание 1
#Создайте numpy array с элементами от числа N до 0 
#(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
import numpy as np


In [25]:
x=input("Введите количество элементов массива:")
xx=int(x)
y = np.arange(xx)
res = y[::-1]
print(res)


Введите количество элементов массива:15
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [70]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. 
#Посчитайте сумму ее значений на диагонали.
z = np.arange(9).reshape((3,3))
#значения по диагонали 
np.diag(np.diag(z))
np.diag(z)
sum_z= sum(np.diag(z))
print(np.diag(z))
print(sum_z)

[0 4 8]
12


In [72]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

# Маcсив-левая часть
mm=np.array([[4.,2.,1.], [1.,3.,0.], [0.,5.,4.]])

# Вектор-правая часть
mv=np.array([4.,12.,-3.])

np.linalg.solve(mm,mv)
             


array([ 0.46666667,  3.84444444, -5.55555556])

In [76]:
#Задание 4
#В материалах занятия раздел “Задача 4 домашнего задания”
#Найдите самого похожего пользователя.
#Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
import matplotlib.pyplot as plt


In [91]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [99]:
# Посетитель о покупках которого известно следующее
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [100]:
def cosine (a,b):
    aLenght = np.linalg.norm(a)
    bLenght = np.linalg.norm(b)
    return np.dot(a,b)/ (aLenght * bLenght)
cosine(users_stats[0],next_user_stats)

   

0.19999999999999996

In [101]:
for i in users_stats:
    print(i, cosine(i,next_user_stats))
    

[2 1 0 0 0 0] 0.19999999999999996
[1 1 2 1 0 0] 0.8451542547285165
[2 0 1 0 0 0] 0.3999999999999999
[1 1 2 1 0 1] 0.7905694150420948
[0 0 1 2 0 0] 0.3999999999999999
[0 0 0 0 0 5] 0.0
[1 0 0 0 0 0] 0.0
[0 1 1 0 0 0] 0.9486832980505138
[0 0 0 1 1 3] 0.0
[1 0 0 2 1 4] 0.0
